"""
EDI Audit Report PDF Generator
Produces a structured, professional audit-grade PDF using ReportLab Platypus.
"""
from __future__ import annotations

import io
from datetime import datetime
from typing import Any

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

# Palette
C_NAVY      = colors.HexColor("#0f172a")
C_INDIGO    = colors.HexColor("#4f46e5")
C_INDIGO_LT = colors.HexColor("#eef2ff")
C_SLATE     = colors.HexColor("#64748b")
C_SLATE_LT  = colors.HexColor("#f8fafc")
C_SLATE_MID = colors.HexColor("#e2e8f0")
C_WHITE     = colors.white
C_GREEN     = colors.HexColor("#16a34a")
C_GREEN_LT  = colors.HexColor("#f0fdf4")
C_RED       = colors.HexColor("#dc2626")
C_RED_LT    = colors.HexColor("#fef2f2")
C_AMBER     = colors.HexColor("#d97706")
C_AMBER_LT  = colors.HexColor("#fffbeb")
C_ROW_ALT   = colors.HexColor("#f1f5f9")

PAGE_W, PAGE_H = letter
MARGIN    = 0.75 * inch
CONTENT_W = PAGE_W - 2 * MARGIN


def _styles():
    return {
        "report_title": ParagraphStyle(
            "report_title", fontName="Helvetica-Bold", fontSize=20,
            textColor=C_NAVY, leading=24, spaceAfter=2),
        "report_subtitle": ParagraphStyle(
            "report_subtitle", fontName="Helvetica", fontSize=10,
            textColor=C_SLATE, leading=14, spaceAfter=0),
        "timestamp": ParagraphStyle(
            "timestamp", fontName="Helvetica", fontSize=8,
            textColor=C_SLATE, alignment=TA_RIGHT),
        "section_title": ParagraphStyle(
            "section_title", fontName="Helvetica-Bold", fontSize=11,
            textColor=C_INDIGO, leading=16, spaceBefore=14, spaceAfter=6),
        "claim_title": ParagraphStyle(
            "claim_title", fontName="Helvetica-Bold", fontSize=9,
            textColor=C_WHITE, leading=13),
        "sub_title": ParagraphStyle(
            "sub_title", fontName="Helvetica-Bold", fontSize=9,
            textColor=C_NAVY, leading=13, spaceBefore=6, spaceAfter=3),
        "normal": ParagraphStyle(
            "normal_body", fontName="Helvetica", fontSize=9,
            textColor=C_NAVY, leading=13),
        "small": ParagraphStyle(
            "small_body", fontName="Helvetica", fontSize=8,
            textColor=C_SLATE, leading=11),
    }


def _divider():
    return HRFlowable(width="100%", thickness=0.5, color=C_SLATE_MID, spaceAfter=6, spaceBefore=2)


def _section_title(text, st):
    return [Paragraph(text.upper(), st["section_title"]), _divider()]


def _p(text, fname="Helvetica", fsize=8.5, color=C_NAVY):
    return Paragraph(str(text) if text else "\u2014",
                     ParagraphStyle("_p", fontName=fname, fontSize=fsize, textColor=color, leading=12))


def _kv_table(rows, col_widths=(2.2 * inch, 4.3 * inch)):
    data = [[_p(k, "Helvetica-Bold"), _p(v)] for k, v in rows]
    t = Table(data, colWidths=list(col_widths), repeatRows=0)
    cmds = [
        ("GRID",         (0, 0), (-1, -1), 0.4, C_SLATE_MID),
        ("LEFTPADDING",  (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING",   (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 5),
        ("VALIGN",       (0, 0), (-1, -1), "TOP"),
    ]
    for i in range(0, len(data), 2):
        cmds.append(("BACKGROUND", (0, i), (-1, i), C_ROW_ALT))
    t.setStyle(TableStyle(cmds))
    return t


def _data_table(cols, rows, col_widths):
    header = [_p(c, "Helvetica-Bold", 8, C_WHITE) for c in cols]
    body   = [[_p(cell, fsize=8) for cell in row] for row in rows]
    data   = [header] + body
    t = Table(data, colWidths=col_widths, repeatRows=1)
    cmds = [
        ("BACKGROUND",   (0, 0), (-1, 0), C_NAVY),
        ("GRID",         (0, 0), (-1, -1), 0.4, C_SLATE_MID),
        ("LEFTPADDING",  (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING",   (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 4),
        ("VALIGN",       (0, 0), (-1, -1), "TOP"),
    ]
    for i in range(1, len(data), 2):
        cmds.append(("BACKGROUND", (0, i), (-1, i), C_ROW_ALT))
    t.setStyle(TableStyle(cmds))
    return t


def _page_footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(C_SLATE)
    canvas.drawCentredString(PAGE_W / 2, 0.42 * inch, f"Page {doc.page}")
    canvas.drawCentredString(PAGE_W / 2, 0.28 * inch, "Generated by SAR EDI Analyzer System")
    canvas.restoreState()


def build_audit_pdf(file_row, parse_row, errors):
    raw_json   = (parse_row.raw_json or {}) if parse_row else {}
    json_exp   = raw_json.get("json_export") or {}
    envelope   = json_exp.get("envelope") or {}
    structured = raw_json.get("structured_data") or []
    tx_type    = (file_row.transaction_type or "").upper()
    st         = _styles()

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=letter,
        leftMargin=MARGIN, rightMargin=MARGIN,
        topMargin=MARGIN, bottomMargin=0.9 * inch,
    )
    story = []

    # 1. HEADER
    now_str = datetime.now().strftime("%B %d, %Y  %H:%M UTC")
    hdr_t = Table(
        [[Paragraph(f"EDI {tx_type} CLAIM REPORT", st["report_title"]),
          Paragraph(now_str, st["timestamp"])]],
        colWidths=[4.5 * inch, 2.5 * inch],
    )
    hdr_t.setStyle(TableStyle([
        ("VALIGN",       (0, 0), (-1, -1), "BOTTOM"),
        ("LEFTPADDING",  (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING",   (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 0),
    ]))
    story.append(hdr_t)
    story.append(Paragraph("Generated Audit Summary", st["report_subtitle"]))
    story.append(Spacer(1, 4))
    story.append(HRFlowable(width="100%", thickness=2, color=C_INDIGO, spaceAfter=10))

    # 2. ENVELOPE DETAILS
    story += _section_title("Envelope Details", st)
    sender   = envelope.get("sender_id")   or (parse_row.sender_id   if parse_row else None) or "N/A"
    receiver = envelope.get("receiver_id") or (parse_row.receiver_id if parse_row else None) or "N/A"
    story.append(_kv_table([
        ("Sender ID",          sender),
        ("Receiver ID",        receiver),
        ("Version",            envelope.get("version") or envelope.get("interchange_version") or "N/A"),
        ("Interchange Date",   envelope.get("interchange_date") or
                               (str(parse_row.interchange_date) if parse_row and parse_row.interchange_date else "N/A")),
        ("Interchange Time",   envelope.get("interchange_time") or envelope.get("bht05_time") or "N/A"),
        ("ISA Control Number", envelope.get("control_number") or envelope.get("isa_control_number") or "N/A"),
        ("GS Control Number",  envelope.get("gs_control_number") or "N/A"),
        ("ST Control Number",  envelope.get("st_control_number") or "N/A"),
    ]))
    story.append(Spacer(1, 10))

    # 3. TRANSACTION OVERVIEW
    story += _section_title("Transaction Summary", st)
    total_charge = sum(float(c.get("total_charge") or 0) for c in structured if isinstance(c, dict))
    valid_label  = "VALID - No errors detected" if file_row.is_valid else f"INVALID - {file_row.error_count} error(s) found"
    valid_color  = C_GREEN if file_row.is_valid else C_RED
    valid_bg     = C_GREEN_LT if file_row.is_valid else C_RED_LT

    ov_t = Table([
        [_p("Transaction Type", "Helvetica-Bold"), _p(tx_type)],
        [_p("Total Claims",     "Helvetica-Bold"), _p(str(len(structured)))],
        [_p("Total Charge",     "Helvetica-Bold"), _p(f"${total_charge:,.2f}", "Helvetica-Bold", 10, C_INDIGO)],
        [_p("Validation Status","Helvetica-Bold"), _p(valid_label, "Helvetica-Bold", 9, valid_color)],
    ], colWidths=[2.2 * inch, 4.3 * inch])
    ov_t.setStyle(TableStyle([
        ("GRID",         (0, 0), (-1, -1), 0.4, C_SLATE_MID),
        ("LEFTPADDING",  (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING",   (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 6),
        ("BACKGROUND",   (0, 0), (-1, 0), C_ROW_ALT),
        ("BACKGROUND",   (0, 2), (-1, 2), C_INDIGO_LT),
        ("BACKGROUND",   (0, 3), (-1, 3), valid_bg),
    ]))
    story.append(ov_t)
    story.append(Spacer(1, 10))

    # 4. CLAIM DETAILS (837 only)
    if structured and isinstance(structured, list) and tx_type in ("837P", "837I"):
        story += _section_title("Claim Details", st)

        for idx, claim in enumerate(structured, 1):
            if not isinstance(claim, dict):
                continue
            pat   = claim.get("patient") or {}
            prov  = claim.get("billing_provider") or {}
            diags = claim.get("diagnoses") or []
            lines = claim.get("service_lines") or []
            claim_charge = float(claim.get("total_charge") or 0)

            # 4.1 Claim header bar
            hdr_bar = Table(
                [[_p(
                    f"CLAIM #{idx}   |   ID: {claim.get('claim_id') or 'N/A'}   |   "
                    f"Freq: {claim.get('claim_frequency') or 'N/A'}   |   "
                    f"Place of Service: {claim.get('place_of_service') or 'N/A'}   |   "
                    f"Total Charge: ${claim_charge:,.2f}",
                    "Helvetica-Bold", 9, C_WHITE
                )]],
                colWidths=[CONTENT_W],
            )
            hdr_bar.setStyle(TableStyle([
                ("BACKGROUND",   (0, 0), (-1, -1), C_INDIGO),
                ("LEFTPADDING",  (0, 0), (-1, -1), 10),
                ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                ("TOPPADDING",   (0, 0), (-1, -1), 7),
                ("BOTTOMPADDING",(0, 0), (-1, -1), 7),
            ]))

            # 4.2 Patient + 4.3 Provider side by side
            half_w = CONTENT_W / 2 - 4
            pat_name = f"{pat.get('first_name','') or ''} {pat.get('last_name','') or ''}".strip() or "N/A"
            pat_t = _kv_table([
                ("Full Name",          pat_name),
                ("Member ID",          pat.get("member_id") or pat.get("subscriber_id") or "N/A"),
                ("Date of Birth",      pat.get("dob") or pat.get("date_of_birth") or "N/A"),
                ("Gender",             pat.get("gender") or "N/A"),
                ("Address",            pat.get("address") or pat.get("address_line1") or "N/A"),
                ("City / State / ZIP", f"{pat.get('city','') or ''}, {pat.get('state','') or ''} {pat.get('zip','') or ''}".strip(", ") or "N/A"),
            ], col_widths=(1.3 * inch, half_w - 1.3 * inch))

            prov_t = _kv_table([
                ("Name",               prov.get("name") or "N/A"),
                ("NPI",                prov.get("npi") or "N/A"),
                ("Tax ID",             prov.get("tax_id") or prov.get("ein") or "N/A"),
                ("Address",            prov.get("address") or prov.get("address_line1") or "N/A"),
                ("City / State / ZIP", f"{prov.get('city','') or ''}, {prov.get('state','') or ''} {prov.get('zip','') or ''}".strip(", ") or "N/A"),
            ], col_widths=(1.3 * inch, half_w - 1.3 * inch))

            side = Table(
                [[_p("Patient Information", "Helvetica-Bold"), _p("Billing Provider", "Helvetica-Bold")],
                 [pat_t, prov_t]],
                colWidths=[half_w, half_w],
            )
            side.setStyle(TableStyle([
                ("LEFTPADDING",  (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING",   (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING",(0, 0), (-1, -1), 0),
                ("VALIGN",       (0, 0), (-1, -1), "TOP"),
            ]))

            # 4.4 Diagnoses
            diag_block = []
            if diags:
                diag_rows = [
                    ["Primary" if i == 0 else "Additional",
                     d.get("code") or "N/A",
                     d.get("qualifier") or "N/A"]
                    for i, d in enumerate(diags)
                ]
                diag_block = [
                    Spacer(1, 6),
                    _p("Diagnoses", "Helvetica-Bold"),
                    Spacer(1, 3),
                    _data_table(["Type", "Code", "Qualifier"], diag_rows,
                                [1.5 * inch, 1.5 * inch, 3.5 * inch]),
                ]

            # 4.5 Service lines
            svc_block = []
            if lines:
                svc_rows = [
                    [l.get("service_date") or l.get("date") or "N/A",
                     l.get("procedure_code") or l.get("cpt") or "N/A",
                     str(l.get("units") or l.get("quantity") or "1"),
                     f"${float(l.get('charge') or l.get('line_charge') or 0):,.2f}"]
                    for l in lines
                ]
                subtotal = sum(float(l.get("charge") or l.get("line_charge") or 0) for l in lines)
                svc_t = _data_table(
                    ["Service Date", "Procedure Code", "Units", "Charge"],
                    svc_rows,
                    [1.6 * inch, 1.8 * inch, 1.2 * inch, 1.9 * inch],
                )
                n = len(svc_rows) + 1  # +1 for header
                sub_row = Table(
                    [[_p(""), _p(""), _p("SUBTOTAL", "Helvetica-Bold", 8, C_INDIGO),
                      _p(f"${subtotal:,.2f}", "Helvetica-Bold", 8, C_INDIGO)]],
                    colWidths=[1.6 * inch, 1.8 * inch, 1.2 * inch, 1.9 * inch],
                )
                sub_row.setStyle(TableStyle([
                    ("BACKGROUND",   (0, 0), (-1, -1), C_INDIGO_LT),
                    ("LINEABOVE",    (0, 0), (-1, 0), 0.8, C_INDIGO),
                    ("LEFTPADDING",  (0, 0), (-1, -1), 6),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                    ("TOPPADDING",   (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING",(0, 0), (-1, -1), 4),
                ]))
                svc_block = [
                    Spacer(1, 6),
                    _p("Service Lines", "Helvetica-Bold"),
                    Spacer(1, 3),
                    svc_t,
                    sub_row,
                ]

            story.append(KeepTogether([
                hdr_bar,
                Spacer(1, 4),
                side,
                *diag_block,
                *svc_block,
                Spacer(1, 14),
            ]))

    # 5. VALIDATION SUMMARY
    story += _section_title("Validation Results", st)
    if not errors:
        ok_t = Table(
            [[_p("No validation errors found. This file passed all HIPAA 5010 checks.",
                 "Helvetica-Bold", 9, C_GREEN)]],
            colWidths=[CONTENT_W],
        )
        ok_t.setStyle(TableStyle([
            ("BACKGROUND",   (0, 0), (-1, -1), C_GREEN_LT),
            ("LEFTPADDING",  (0, 0), (-1, -1), 12),
            ("TOPPADDING",   (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING",(0, 0), (-1, -1), 8),
            ("GRID",         (0, 0), (-1, -1), 0.4, C_GREEN),
        ]))
        story.append(ok_t)
    else:
        err_rows = [
            [(e.severity or "error").upper(), e.error_code or "—", e.segment or "—", e.error_message or "—"]
            for e in errors
        ]
        err_t = _data_table(
            ["Severity", "Error Code", "Segment", "Description"],
            err_rows,
            [0.9 * inch, 1.2 * inch, 0.9 * inch, 3.5 * inch],
        )
        for i, e in enumerate(errors, 1):
            sev = (e.severity or "error").lower()
            bg = C_RED_LT if sev == "error" else C_AMBER_LT
            err_t.setStyle(TableStyle([("BACKGROUND", (0, i), (0, i), bg)]))
        story.append(err_t)

    story.append(Spacer(1, 20))
    doc.build(story, onFirstPage=_page_footer, onLaterPages=_page_footer)
    return buf.getvalue()
